
name: Deploy

on:
  push:
    tags:
    - v*

jobs:
  deploy-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup repository
      run: |
        pip install conan
        conan remote add conan-iceshard https://conan.iceshard.net/
        conan remote add conan-bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - name: Build
      run: |
        conan create . ice-build-tools/0.0.2@iceshard/stable
    - name: Deploy
      run: |
        conan user iceshard -r conan-iceshard -p ${{ secrets.CONAN_PASSWORD }}
        conan upload -r conan-iceshard ice-build-tools/0.0.2@iceshard/stable --all
