name: Validation

on:
  push:
    branches:
    - master

jobs:
  validation-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup repository
      run: |
        pip3 install setuptools
        pip3 install conan
        ~/.local/bin/conan remote add conan-iceshard https://conan.iceshard.net/
        ~/.local/bin/conan remote add conan-bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        ~/.local/bin/conan profile new --detect default
        ~/.local/bin/conan profile update settings.compiler=clang default
        ~/.local/bin/conan profile update settings.compiler.version=9 default
        ~/.local/bin/conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: Create package
      run: |
        ~/.local/bin/conan create . ice-build-tools/0.4.3@iceshard/stable
    - name: Success
      run: |
        echo Validation successful
