name: Validation

on:
  push:
    branches:
    - master

jobs:
  validation-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup repository
      run: |
        pip3 install setuptools
        pip3 install conan
        ~/.local/bin/conan config install https://github.com/iceshard-engine/conan-config.git
    - name: Create (lua-5.1.5, clang-10)
      run: |
        ~/.local/bin/conan create . ice-build-tools/0.4.5@iceshard/stable --profile clang-10.0-linux-x86_64
    - name: Success
      run: |
        echo Validation successful
