name: Validation

on:
  push:
    branches:
    - master

jobs:
  validation-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup repository
      run: |
        pip install conan
        conan remote add conan-iceshard https://conan.iceshard.net/
        conan remote add conan-bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - name: Create package
      run: |
        conan create . ice-build-tools/0.3.0@iceshard/stable
    - name: Success
      run: |
        echo Validation successful
